version: 0.0
os: linux
files:
  - source: output/app.jar
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/scripts

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ec2-user

  AfterInstall:
    - location: scripts/start.sh
      timeout: 30
      runas: ec2-user